// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/world-map/WorldMapMatte.tsx": () => import("../components/mockups/world-map/WorldMapMatte.tsx"),
  "./components/mockups/world-map/WorldMapMetallic.tsx": () => import("../components/mockups/world-map/WorldMapMetallic.tsx")
};
